services:
  tweet-database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tweet
    ports:
      - "5437:5432"
    volumes:
      - fyp_data:/var/lib/postgresql/data
  tweet-backend:
    build: ../fyp-backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7000:8000"
    depends_on:
      - tweet-database
    environment:
      - DB_HOST=tweet-database
      - DB_PORT=5432
      - DB_NAME=tweet
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - TWEET_EXTRACTOR_URL=http://tweet-extraction:5000
    volumes:
      - ../fyp-backend/api:/app/api
      - ../fyp-backend/backend45:/app/backend45
      - ../fyp-backend/ml_model:/app/ml_model
      - ../fyp-backend/tweet:/app/tweet
  tweet-extraction:
    build: ../fyp-tweet-extraction
    command: bash -c "python main.py"
    ports:
      - "5000:5000"
volumes:
  fyp_data:
    